name: Vue CI

on:
  push:
    branches: [ master, develop ]
    paths: 
      - 'SmartHub/SmartHub.Ui/**'
  pull_request:
    branches: [ master, develop  ]

jobs:
  Install_Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Use latest Node.js version
      uses: actions/setup-node@master
    
    - name: Move to src folder
      run: | 
            cd SmartHub/SmartHub.Ui
            ls
          
    - name: Installing project dependencies
      run: npm install
    
    - name: Building the project
      run: npm run build
